---
os:
  - linux

services:
  - docker

language: python

python:
  - 3.6

sudo: required

before_install:
  - cd topo-extra-files/host/
  - docker build -t alpine-host .
  - cd ../../

install:
  - pip install git+https://github.com/networkop/arista-ceos-topo.git@dev
  - sudo pip install git+https://github.com/networkop/arista-ceos-topo.git@dev

jobs:
  include:
    - stage: Version 1 testing
      script:
        - sudo python -m pip list
        - sudo -E python -m pip list
        - sudo PATH=$(dirname `which python`):$PATH python -m pip list
        - sudo -E PATH=$(dirname `which python`):$PATH python -m pip list
        - sudo -E test/v1/v1-t1.sh
    - stage: Version 2 testing
      script:
        - sudo -E test/v2/v2-t1.sh

notifications:
  email: false