---
os:
  - linux

services:
  - docker

language: python

python:
  - 3.6

sudo: false

before_install:
  - ls
  - pwd
  - cd arista-ceos-topo/arista-ceos-files/host/
  - docker build -t alpine-host .
install:
  - pip install git+https://github.com/networkop/arista-ceos-topo.git@dev

script:
  - ceos-topo --create --debug test/v1/t1.yml
  - docker exec -it t1_host-1 sudo ping -c 3 12.12.12.2
  - ceos-topo --destroy --debug test/v1/t1.yml
