---
os:
  - linux

services:
  - docker

language: python

python:
  - 3.6

sudo: required

before_install:
  - cd topo-extra-files/host/
  - docker build -t alpine-host .
  - cd ../../

install:
  - sudo pip install git+https://github.com/networkop/arista-ceos-topo.git@dev
  - sudo pip install pyyaml

jobs:
  include:
    - stage: Version 1 testing
      script:
        - test/v1/v1-t1.sh
    - stage: Version 2 testing
      script:
        - sudo test/v2/v2-t1.sh

notifications:
  email: false